#!/usr/bin/python
# -*- coding: utf-8 -*-
# pylint: disable=W0703

# pylint messes up on readline for some reason
# pylint: disable=no-member

# pylint is silly with relative imports
# pylint: disable=relative-import

# decomposing comprehensions would be bad
# pylint: disable=line-too-long

# all code is client-side run under the user's account
# pylint: disable=eval-used

# pylint doesn't know where files are being imported
# pylint: disable=no-name-in-module
# pylint: disable=import-error
# pylint: disable=ungrouped-imports

"""
[ergonomica.py]

The ergonomica runtime.
"""

import os
import re
import sys
import traceback
import socket

# lib/lib
try:
    from lib import readline
except ImportError:
    import readline

# lib/lang
from lib.lang import completer
from lib.lang.parser import tokenize
from lib.lang.operator import run_operator
from lib.lang.statement import get_statement
from lib.lang.error_handler import get_error_message
from lib.lang.environment import Environment
from lib.lang.error import ErgonomicaError
from lib.lang.runtime import Runtime

# lib/load
from lib.load.load_commands import verbs
from lib.load.load_config import load_config

# lib/misc
from lib.misc.arguments import print_arguments
from lib.misc.arguments import process_arguments

# allow autocomplete (tab)
readline.set_completer(completer.completer)
readline.parse_and_bind("tab: complete")

# initialize environment
ENV = Environment()
ENV.verbs = verbs

# read config file
try:
    LINES = open(os.path.expanduser("~/.ergo/.ergo_profile"), 'r').read().split("\n")
    LINES = [x for x in LINES if (x != "") and (x[0] != "#")] # filter out comments
    load_config(ENV, LINES)
except IOError as error:
    print "An error occurred when accessing .ergo_profile: " + str(error)

# read history
try:
    HIST_FILE = open(os.path.expanduser("~/.ergo/.ergo_history"), 'a')
    HIST = open(os.path.expanduser("~/.ergo/.ergo_history"), "r").read().split("\n")
    for item in HIST[:-1]:
        readline.add_history(item)
except IOError as error:
    print "An error occured while accessing ~/.ergo_history: " + str(error)

def ergo(stdin):
    """Main ergonomica runtime."""

    #evaluate variables
    try:
        matches = re.search(r"\$\((.*?)\)", stdin).groups()
        for match in matches:
            stdin = stdin.replace("$(%s)" % (match), verbs.namespace[match])
    except AttributeError:
        pass

    stdout = []

    runtime = Runtime()
    
    num_blocks = len(stdin.split("->"))
    blocks = stdin.split("->")
    tokenized_blocks = [tokenize(block) for block in stdin.split("->")]
    for i in range(0, len(blocks)):
        try:
            num_blocks -= 1
            statement = get_statement(blocks[i])
            evaluated_operator = run_operator(blocks[i], runtime)
            
            if blocks[i].strip() == "":
                pass
            elif evaluated_operator:
                stdout = evaluated_operator
            elif statement == "run":
                lines = [open(_file, "r").read().split("\n") for _file in tokenized_blocks[i][0][1:]]
                flattened_lines = [item for sublist in lines for item in sublist]
                stdout = map(ergo, flattened_lines)
            else:
                func = verbs[tokenized_blocks[i][0][0]]
                args = runtime.last_args + tokenized_blocks[i][0][1:]
                runtime.last_kwargs.update({s.split(":")[0]:s.split(":")[1] for s in tokenized_blocks[i][1]})
                kwargs = runtime.last_kwargs
                stdout = func(ENV, args, kwargs)

            # filter out none values
            try:
                if isinstance(stdout, list):
                    stdout = [x for x in stdout if x != None]
            except TypeError:
                stdout = []

        except Exception, error:
            # if no ergonomica error message can be generated
            if isinstance(error, ErgonomicaError):
                print >> sys.stderr, error
                return
            if not get_error_message(blocks[i]):
                # fallback to python
                stdout = [traceback.format_exc()]
            else:
                stdout = get_error_message(blocks[i])
        if not isinstance(stdout, list):
            runtime.last_args = [stdout]
            if (not num_blocks) and (stdout != None):
                print >> sys.stderr, stdout
        else:
            runtime.last_args = []
            for item in stdout:
                runtime.last_args.append(item)
                if not num_blocks:
                    print item

GOAL = process_arguments(sys.argv[1:])

if GOAL == "help":
    print_arguments()
    ENV.run = False

if GOAL == "run a file":
    LINES = open(sys.argv[2], "r").read().split("\n")
    map(ergo, LINES)

if GOAL == "run strings":
    map(ergo, sys.argv[2:])

if GOAL == "shell":
    while ENV.run:
        try:
            ergo(raw_input(ENV.prompt.replace("\\h", socket.gethostname()).replace("\\u", ENV.user).replace("\\w", ENV.directory)))
        except KeyboardInterrupt:
            print "\n^C"
